### ISSUE TITLE
 ./build-iso.sh: line 36: patch: command not found

### ISSUE THREAD

**Issue by MrAmos123** [core-process/linux-unattended-installation#17]
```
dos2unix: converting file ./isolinux.cfg to Unix format...
./build-iso.sh: line 36: patch: command not found
root@TestUbuntu-VM:~/linux-unattended-installation-master/ubuntu/18.04#
```

Image running: `Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-46-generic x86_64)` 

Can you please tell me what dependency I'm missing? I installed the recommended ones from the readme.md.

Cheers!

**Comment by maurodelazeri** [comment]
All you need to do is `yum install patch` I assume you are using Centos

**Comment by MrAmos123** [comment]
Whoops, that fixed it. Thanks!

`apt install patch`
