### ISSUE TITLE
Could I use a normal ISO instead of netboot mini.iso to speed up installation?

### ISSUE THREAD

**Issue by orange888** [core-process/linux-unattended-installation#19]
How to speed up the installation process?
Could I use a normal ISO instead of netboot mini.iso to speed up installation?

Thanks.

**Comment by dentarg** [comment]
Yes

**Comment by orange888** [comment]
> Yes

Could you show an example?
Which ISO can I use to speed up the process?

Thank you.

**Comment by core-process** [comment]
@orange888 Have a look at https://github.com/core-process/linux-unattended-installation/issues/3. Does it help?
