### ISSUE TITLE
Feature request: generate hybrid ISO file, e.g. to produce bootable USB drives

### ISSUE THREAD

**Issue by atripes** [core-process/linux-unattended-installation#2]
I followed the instructions like so:
```
user$ git clone https://github.com/core-process/linux-unattended-installation.git
user$ ./ubuntu/18.04/build-iso.sh /home/user/.ssh/id_rsa.pub /tmp/bootable_ubuntu1804.iso
```
When trying to burn the iso with Etcher (official ubuntu usb-stick-creation software recommendation) it complains that this is not a bootable iso. I ignored this at first and did it anyway, but wasn't able to boot with this.  
Is this *meant* to create a bootable iso?  

Best,
Alex

**Comment by core-process** [comment]
Hey @atripes, yes, it is meant to be used as bootable ISO. I used these generated ISOs to boot hundreds of KVM and VirtualBox based VMs as well as a few physical VMs (via DVD, not USB Stick). Try it yourself, works fine.

I never tried to make a bootable USB stick out of the generated ISOs. Will try this myself next week.

In case you have any ideas how to fix this issue, please let me know!

**Comment by core-process** [comment]
@atripes To make it bootable via USB stick we need to generate a hybrid ISO file. The currently produced ISO file is only bootable from optical media and within VMs.

**Comment by core-process** [comment]
This might help us to reach the goal: https://ubuntuforums.org/showthread.php?t=1980215

**Comment by atripes** [comment]
I might have to take that back. Tinkering with the patched image may have had the effect that the installation is no longer unattended I am afraid.  
It failed to obtain an IP address via DHCP and printed all of that to the standard Ubuntu Installation GUI. I can no longer be sure that the preseed file has an actual effect. I have never seen it work, so I might be misjudging here.

**Comment by core-process** [comment]
@atripes thanks for your post. I will have a look this week. I am sure we can fix this.

**Comment by core-process** [comment]
@atripes I started a new branch for this feature: https://github.com/core-process/linux-unattended-installation/compare/feature/hybrid-iso

So far I switched from mkisofs to xorriso and verified that the ISO still works for my own use cases. Seems fine to me. What I did not check is, whether it will work in combination with USB devices already. At least it gets recognized by Etcher now, but I did not actually copied it to a USB device.

You need to run `sudo apt-get install isolinux xorriso` before you can use the updated `ubuntu/18.04/build-iso.sh` script.

I will continue my work the day after tomorrow.
