### ISSUE TITLE
relative path for ssh key

### ISSUE THREAD

**Issue by jaydouble** [core-process/linux-unattended-installation#21]
when adding a ssh key, it needs to be relative to the temp dir.
So I made myself an enhancement to the build-iso.sh script, that I would like to share (tested on my macbook):
```bash
function getRealPath {
    path=$1
    perl << EOF
#!/usr/bin/perl
use Cwd 'abs_path';
\$realfilepath = abs_path("$path");
print "\$realfilepath\n";
EOF
}


# get parameters
SSH_PUBLIC_KEY_FILE=${1:-"$HOME/.ssh/id_rsa.pub"}
TARGET_ISO=${2:-"`pwd`/ubuntu-18.04-netboot-amd64-unattended.iso"}
# get realpath of public key
SSH_PUBLIC_KEY_FILE=$(getRealPath $SSH_PUBLIC_KEY_FILE)
# get realpath of target iso file
TARGET_ISO=$(getRealPath $TARGET_ISO)
```

**Comment by hadrien-toma** [comment]
I think this is out of the scope of this repository, having absolute path is a good practice and let you built it from a relative one if you want.

By the way, on most of the Linux systems, you can do

```sh
scriptDir=`dirname $0 | while read a; do cd $a && pwd && break; done`
```

So you can use scriptDir to build your absolute path from the place where the script is.

Can we close this issue @core-process ?
