### ISSUE TITLE
Feature request: improved binary path lookup mechanism, e.g. support mkisofs vs genisoimage

### ISSUE THREAD

**Issue by tachang** [core-process/linux-unattended-installation#4]
So this is really minor but on a debian install genisoimage is the name of mkisofs.

Basically they are the same really but not sure why one is named mkisofs and one is called genisoimage.

What would be a good way to detect if you have either of them and use it?

**Comment by core-process** [comment]
@tachang we could use the following lookup mechanism (works in `bash`):

```shell
GENISOIMAGE_PATH=$(type -P genisoimage || type -P mkisofs)
```

**Comment by core-process** [comment]
We switched to `xorriso`, therefore `genisoimage` vs. `mkisofs` lookup is no longer required. I added lookup for specific binaries anyway (https://github.com/core-process/linux-unattended-installation/commit/154af3c6929b7c6e0b19861b0b46f96f16e9f42f).
