### ISSUE TITLE
Feature request: Add UEFI boot capability

### ISSUE THREAD

**Issue by brucerbwoods** [core-process/linux-unattended-installation#5]
Newer hardware often prefers UEFI, some of it doesn't even include a legacy BIOS mode.
This would also be helpful to those wishing to do minimal/task specific Desktop installs using the netboot image.

Its been known this is possible to do with the netboot mini.iso for a good while, and its curious that canonical haven't included it as part of the image build process yet.
See:- https://askubuntu.com/questions/738305/why-doesnt-the-minimal-image-support-uefi
and https://bugs.launchpad.net/ubuntu/+source/debian-installer/+bug/1429030

This should be quite possible to add as part of the build-iso.sh script as it does unpack the source iso anyway.

Preseed would also need adjustment to match the manual steps described here:- https://www.onetransistor.eu/2015/12/install-ubuntu-minimal-cd-uefi-enabled.html

**Comment by core-process** [comment]
@brucerbwoods I was able to create an UEFI-bootable ISO file. But the resulting installation is not UEFI-bootable yet (at least not, when trying with VirtualBox). Do you have an idea?

See https://github.com/core-process/linux-unattended-installation/compare/feature/uefi

**Comment by core-process** [comment]
@brucerbwoods Thanks for your response. When I perform an UEFI-mode installation with VirtualBox, the resulting installation is not in UEFI-mode. I have to disable UEFI in the VM configuration to boot the resulting installation (it boots fine then). When I inspect the partition table, the EFI partition is simply missing. Even though the recipe works fine otherwise.

Please let me know how if it is the same, when you perform an installation on a physical machine.

**Comment by core-process** [comment]
@brucerbwoods did you try it yourself?

**Comment by brucerbwoods** [comment]
Apologies, its been an exhausting week at work.~
I have installed two virtual machines to compare partitions and their contents but not had time to do the comparison yet. One was installed with an iso generated using the above mentioned branch and the other with the normal server iso.
I'm actually unsure so far if the iso built with the above branch even boots in UEFI mode at all, and in the installer environment it is difficult to be sure. 
I will report back here when I've been able to inspect and compare the VM's.

**Comment by core-process** [comment]
@brucerbwoods when you enable EFI in virtualbox it is EFI only. So you can be sure it is booting in EFI mode. Also the boot manager screen looks different when you boot in EFI. It is easy to observe. I will post two screenshots later.

**Comment by brucerbwoods** [comment]
Aaah ok.
As I say, I will compare the two installs when I get a chance soon and share any (hopefully) relevant findings here.

**Comment by core-process** [comment]
@brucerbwoods 

BIOS mode:
![image](https://user-images.githubusercontent.com/1226918/41151991-b1183fc6-6b12-11e8-8aa3-b5cebbecc8f6.png)

EFI mode:
![image](https://user-images.githubusercontent.com/1226918/41152030-c3cec96e-6b12-11e8-926f-0dfe0360adf1.png)

**Comment by core-process** [comment]
@brucerbwoods I fixed the issue. It was a simple mistake in the partitioning recipe: https://github.com/core-process/linux-unattended-installation/commit/80662615c5d663f409433b8e5b4c00edb2b7ca95. Just pull the latest revision from the `feature/uefi` branch.

```sh
# clone branch feature/uefi
git clone -b feature/uefi https://github.com/core-process/linux-unattended-installation.git

# build iso
./linux-unattended-installation/ubuntu/18.04/build-iso.sh
```

**Comment by brucerbwoods** [comment]
Excellent! Thankyou!
I'll get testing this branch with my own preseeds :)
