### ISSUE TITLE
Hangs on Grub Boot Loader Install

### ISSUE THREAD

**Issue by s8i** [core-process/linux-unattended-installation#7]
The machine I'm installing to is a dev machine and I don't care what drives I reformat. 
It does have Linux installed to the nvme drive already. Erasing is no problem here.

**Drives we have** 
1 NVME, usually our OS is installed here `/dev/nvme0n1`
1 SSD, fast archive storage `/dev/sdb`
1 HDD, slow archive storage `/dev/sda`

**Bios boot order is**:
NVME
SSD
~HDD~ is *boot disabled*

There is a grub partition already because of the pre-existing install.   
Maybe this is the source of the issue for me.   
A desirable feature for some would be to format all drives first

Unplugging  all drives except **nvme0n1** and changing the `predeed.cfg` from `/dev/sda` to `/dev/nvme0n1` has the same issue and hangs at 66% and doesn't go any further

Line 73
```bash
### Partitioning
d-i preseed/early_command string umount /media || true
d-i partman-auto/disk string /dev/nvme0n1
 ...
```
&

Line 99
```bash
### Grub
d-i grub-installer/bootdev string /dev/nvme0n1
d-i grub-installer/only_debian boolean true
d-i grub-installer/with_other_os boolean true
 ...
```

Any thoughts Niklas?
Again, great work!

![grub-install-hang](https://user-images.githubusercontent.com/17534521/42793011-1d007ea6-89cc-11e8-896d-b4d9ccd938c4.jpg)

**Comment by Hammatt** [comment]
I'm running into the same issue! Also using an nvme drive, I wonder if this is related?

**Comment by brucerbwoods** [comment]
I am also running into this issue whilst installing on a virtual machine.

**Comment by core-process** [comment]
@Hammatt and @brucerbwoods based on [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853187#25) information I was able to implement the following workaround: https://github.com/core-process/linux-unattended-installation/blob/master/ubuntu/18.04/custom/preseed.cfg#L82
